---
- hosts: all
  name: Ansible play
  user: ec2-user

  tasks:

    - name: Installing httpd
      shell: sudo yum install httpd -y
      args:
        executable: /bin/bash
    - name: Installing php
      shell: sudo yum install php -y
      args:
        executable: /bin/bash
    - name: Installing php-mysqlnd
      shell: sudo yum install php-mysqlnd -y
      args:
        executable: /bin/bash
    - name: Installing php-gd
      shell: sudo yum install php-gd -y
      args:
        executable: /bin/bash
    - name: Installing php-xml
      shell: sudo yum install php-xml -y
      args:
        executable: /bin/bash
    - name: Installing mariadb-server
      shell: sudo yum install mariadb-server -y
      args:
        executable: /bin/bash
    - name: Instalingl mariadb
      shell: sudo yum install mariadb -y
      args:
        executable: /bin/bash
    - name: Installing php-mbstring
      shell: sudo yum install php-mbstring -y
      args:
        executable: /bin/bash
    - name: Installing php-json
      shell: sudo yum install php-json -y
      args:
        executable: /bin/bash
    - name: Installing firewalld
      shell: sudo yum install firewalld -y
      args:
        executable: /bin/bash
    - name: Starting firewall (services)
      shell: sudo systemctl start firewalld && sudo systemctl enable firewalld
      args:
        executable: /bin/bash




    - name: Database (MySQL) start mariadb
      shell: sudo systemctl start mariadb
      ignore_errors: True
      args:
        executable: /bin/bash


    - name: Database (MySQL) secure_installation
      shell: sudo mysql_secure_installation \n n
      ignore_errors: True
      args:
        ececutable: /bin/bash


    - name: CUSTOM_MYSQL_SCRIPT (For user and database creation)
      shell: /home/ec2-user/ansible/create-mysql.bash
      become: true
      become_method: sudo
      become_user: root
      ignore_errors: True
      args:
        executable: /bin/bash


    - name: Enabling mariadb and apache  database daemons (services)
      shell: sudo systemctl enable mariadb && sudo systemctl enable httpd
      ignore_errors: True
      args:
        executable: /bin/bash


    - name: Download MediaWiki
      shell: curl "https://releases.wikimedia.org/mediawiki/1.35/mediawiki-1.35.0.tar.gz" --output mediawiki-1.35.0.tar.gz
      ignore_errors: True
      args:
        chdir: /home/ec2-user/ansible

    - name: Download the GPG signature
      shell: curl https://releases.wikimedia.org/mediawiki/1.35/mediawiki-1.35.0.tar.gz.sig --output mediawiki-1.35.0.tar.gz.sig
      ignore_errors: True
      args:
        chdir: /home/ec2-user/ansible


    - name: Signature Verification
      shell: gpg --verify mediawiki-1.35.0.tar.gz.sig mediawiki-1.35.0.tar.gz
      ignore_errors: True
      args:
        chdir: /home/ec2-user/ansible


    - name: Unzipping MediaWiki
      shell: sudo tar -zxvf /home/ec2-user/ansible/mediawiki-1.35.0.tar.gz
      ignore_errors: True
      args:
        chdir: /var/www

    - name: Creating Softlink
      shell: sudo ln -s mediawiki-1.35.0/ mediawiki
      ignore_errors: True
      args:
        chdir: /var/www



    - name: Changing Ownership assuming  /var/www to /var/www/mediawiki
      shell: sudo chown -R apache:apache /var/www/mediawiki-1.35.0
      ignore_errors: True
      args:
        chdir: /var/www

    - name: Restarting Apache
      shell: sudo service httpd restart
      ignore_errors: True
      args:
        executable: /bin/bash

    - name: Firewall configuration
      shell: sudo firewall-cmd --permanent --zone=public --add-service=http && sudo firewall-cmd --permanent --zone=public --add-service=https
      ignore_errors: True
      args:
        executable: /bin/bash


    - name: Enabling both the https and http services
      shell: sudo systemctl restart firewalld
      ignore_errors: True
      args:
        executable: /bin/bash
